-- Order summaries generated by AI
CREATE TABLE order_summaries (
    id              UUID PRIMARY KEY,
    order_id        UUID NOT NULL UNIQUE,
    status          VARCHAR(30) NOT NULL,
    summary_text    TEXT NOT NULL,
    model_used      VARCHAR(60) NOT NULL,
    prompt_tokens   INT,
    completion_tokens INT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_order_summaries_order_id ON order_summaries (order_id);

-- Idempotency guard for consumed Kafka events
CREATE TABLE processed_events (
    event_id        UUID PRIMARY KEY,
    processed_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
