#!/bin/sh
#
# Gradle start up script for POSIX generated by Gradle.
#
# Important for running:
#
# (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#     noncompliant, but you have some other POSIX-compliant shell such as ksh or
#     bash, then to run this script, type that shell name before the whole
#     command line, like:
#
#         ksh Gradle
#
#     Busybox and similar reduced shells will NOT work, because this script
#     requires all of these POSIX shell features:
#       * functions;
#       * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#         «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#       * compound commands having a testable exit status, especially «case»;
#       * various built-in commands including «command», «set», and «ulimit».
#
# Important for modifying:
#
# (2) In accordance to the output of «uname -s» on target platforms, this script
#     divides the target platforms into two major categories, and that is:
#     * a POSIX-compliant platform (including UNIX, Linux, MacOS/Darwin, Cygwin, etc)
#     * a Windows NT platform (including Windows XP, Windows 7, Windows 10, etc)
#
#     Please note that the Microsoft Windows Subsystem for Linux (WSL) is a
#     special case: it will be treated as a POSIX platform.

set -e

GRADLE_APP_BASE_NAME=${0##*/}
GRADLE_APP_HOME=$( cd "${0%"$GRADLE_APP_BASE_NAME"}" && pwd -P ) || exit

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

APP_ARGS=( "$@" )

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname -s )" in          #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$GRADLE_APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
        ;;
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     shell script including quotes and variable substitutions, so put them in
#     double quotes to make sure that they are evaluated. To learn how to
#     write shell script fragments that work with eval, see docs.gradle.org/...
#   * Make sure all arguments are properly quoted with single quotes to
#     prevent word splitting and glob expansion.

set -- \
    "-Dorg.gradle.appname=$GRADLE_APP_BASE_NAME" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "${APP_ARGS[@]}"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
#
# In Bash we could simply go:
#
#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
#   set -- "${ARGS[@]}" "$@"
#
# but POSIX shell has neither arrays nor command substitution, so instead we
# post-process each arg (modifying $@) to workaround quoting.
#
# Potentially problematic situations:
#
#  - In Bash, in particular all known versions 3.x through 5.x, even when the initial
#    parsing of the variable is done by $(), the later argument parsing
#    is done by the Bash-specific IFS parsing. As a result, to make things consistent,
#    we use double quotes to ensure the variable is processed as a single, quoted string.
#
eval "set -- $(
        printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
        xargs -n1 |
        sed ' s~[^-[:alnum:]+,./:=@_]~\\&~g; ' |
        tr '\n' ' '
    )" '"$@"'

exec "$JAVACMD" "$@"
